### ISSUE TITLE
429 too many requests

### ISSUE THREAD

**Issue by Mokson** [vitalik/python-monobank#3]
При деяких спробах дістати данні вилітає помилка 429 Too Many Requests
Було б добре додати цей кейс в лібу

**Comment by FOUREX** [comment]
> При деяких спробах дістати данні вилітає помилка 429 Too Many Requests Було б добре додати цей кейс в лібу

Використовуй вебхуки

**Comment by vitalik** [comment]
@Mokson 

there is a case - you can simply handle exception and use sleep :

```Python
try:
    mono.get_statements(....)
except monobank.TooManyRequests:
    time.sleep(1)
    # try again:
    mono.get_statements(....)
```

you can wrap it into some custom decorator

or use [ratelimiter](https://pypi.org/project/ratelimiter/)

Note: corporate API does not have rate limits (at leas it did not back then)
